### PR TITLE
Added Apple TV & Apple Watch kernelcaches

### PR DESCRIPTION
**Pull request by matteyeux**
Yep there are unencrypted too

### CODE REVIEW

**Comment by mwoolweaver** [comment]
Do you think you could decompile them as well? There are instructions [here](https://www.reddit.com/r/jailbreak/comments/4nyz1p/discussion_decrypted_kernel_cache_ios_10/d48cgd7) 

If not it's ok

**Comment by matteyeux** [comment]
They are already decompiled/decompressed

**Comment by mwoolweaver** [comment]
Do what?

**Comment by mwoolweaver** [comment]
No, Apple shipped them un-encrypted. To get them to a human readable form you have to follow the instructions in the link I provided above. And you will end up will end up with files like what are seen [here](https://github.com/iOS-10-Stuffs/Disassembled-Kernels).

**Comment by matteyeux** [comment]
Sorry, when I said they are already decompressed, I mean I already did it

**Comment by mwoolweaver** [comment]
Ahh ok. Sorry for my confusion. Also feel free to submit them in a pull request to [Disassembled-Kernels](https://github.com/iOS-10-Stuffs/Disassembled-Kernels).

**Pull request merged**
